### ISSUE TITLE
Gem ignoring 'emulated' property for custom psuedoclasses when combining pseudoclasses

### ISSUE THREAD

**Issue by fresheneesz** [Tixit/Gem.js#11]
I have the following inside a style:

```
                    $$hover: {
                        backgroundColor: 'white'
                    },
                    '$$label(savedSearchText)': {
                        fontSize: 12,
                        color: 'gray'
                    },
```

And I'm getting the following exception:

```
Error: Failed to execute 'insertRule' on 'CSSStyleSheet': Failed to parse the rule '._ComponentStyle_1105:label(savedSearchText):hover { }'.
    at Error (native)
    at addRuleToSheet (https://localhost:9000/App.bundle.js:4775:21)
    at addRule (https://localhost:9000/App.bundle.js:4733:18)
    at setCss (https://localhost:9000/App.bundle.js:4722:21)
    at createPseudoClassRules (https://localhost:9000/App.bundle.js:4906:18)
    at HashMap.<anonymous> (https://localhost:9000/App.bundle.js:4831:22)
    at HashMap.forEach (https://localhost:9000/App.bundle.js:13104:11)
    at HashMap.forEach (https://localhost:9000/App.bundle.js:13127:8)
    at createNativePseudoclasses (https://localhost:9000/App.bundle.js:4817:38)
    at createNativeCssInfo (https://localhost:9000/App.bundle.js:4415:40)
```

**Comment by fresheneesz** [comment]
This happens when the custom pseudoclass is in a style being mixed into another one like this:

```
style1.mix({
  '$$label(whatever)': {
    color: 'gray'
   }
})
```
